server:
  port: 8082
spring:
  application:
    name: notification
  zipkin:
    base-url: http://localhost:9411
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/notification
    username: thiago
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key